ramirez60/fourwinds

static/css/style.css
website/templates/top_navbar.html
website/templates/website/contact-us.html
website/templates/website/our-story.html
website/templates/website/request_quote.html
website/templates/website/travel.html
website/urls.py
website/views.py

request a quote page
travel page
contact us page
our story page

Adding missing templates

---

fourwinds/settings.py
static/css/style.css
website/models.py
website/templates/testimonials.html
website/templates/top_navbar.html
website/templates/website/base.html
website/templates/website/travel-ajax.html

Working on responsive support
2hr

Responsive

---

website/templates/footer.html
website/templates/top_header.html

- Link header logo to homepage

- Update CA office address in footer

---

website/templates/blog/tags/categories.html

- Changed topic links to vertical view

Changed topic list to vertical view

---

website/templates/website/tags/testimonials.html

- Fixed display of date in testimonial

Fixed testimonial date display

---

fourwinds/static/css/style.css
fourwinds/static/sass/_header.scss

- Subpages links are displayed in navigation on hover

Added display of subpages on link hover in navigation

---

fourwinds/static/css/style.css
fourwinds/static/sass/_landing.scss
home/templates/home/tags/quick_contact_form.html

- Capitalized form title
- Switched color of form header and button
- Added grey background to form

Added enhancements to quick contact form

---

fourwinds/static/css/style.css
fourwinds/static/sass/_pages.scss
fourwinds/templates/base.html

- Added breadcrumb on pages except in homepage

Added breadcrumb

---

fourwinds/static/css/style.css
fourwinds/static/sass/_pages.scss
home/templates/home/tags/main_slider.html
home/templates/home/tags/quick_contact_form.html

- Prepopulate get quote form with quick contact form data

Redirect quick contact form to get quote form

---

home/templates/home/tags/quick_contact_form.html

- Matched fields of quick contact form to get quote form

Fixed quick contact form fields

---

home/templates/home/tags/main_slider.html
home/templatetags/home_tags.py

- Link of browse tours in homepage is now dynamic

Added dynamic link to browse tours in homepage

---

home/templatetags/home_tags.py

- Fixed broken link on browse tours

Fixed broken link to tours collection page

---

fourwinds/static/css/style.css
fourwinds/static/sass/_pages.scss

- Reduced gap between breadcrumb and content

Reduced gap between breadcrumb and content

---

home/templatetags/home_tags.py
website/templates/website/tags/side_testimonials.html
website/templates/website/tags/testimonials.html

- Testimonial text is truncated on homepage and on sidebar of some pages

Truncated testimonial text

---

fourwinds/static/css/style.css
fourwinds/static/sass/_pages.scss
website/models.py
website/templates/website/website_tour_collection_index_page.html

- Changed tours collection index to three columns
- Changed tour collection items to two columns in the center column of tours collection index
- Only tours collection item page types are displayed in index page of tours collection

Tours collection index changed to three columns and fixed blank items

---

fourwinds/static/css/style.css
fourwinds/static/sass/_landing.scss

- Emphasized carousel navigation arrow

Added emphasis to carousel navigation arrows

---

fourwinds/static/css/style.css
fourwinds/static/sass/_pages.scss
website/models.py
website/templates/website/website_testimonals_index_page.html
website/templates/website/website_testimonial_page.html

- Fix quotations and heading
- Added pager

Enhance testimonials page

---

website/templates/website/website_safety_insurance_index_page.html

Restore pdf image

---

fourwinds/static/css/style.css
fourwinds/static/sass/_landing.scss

Fix carousel in mobile view

---

website/models.py

- Order testimonials by most recent

Order testimonials by most recent

---

fourwinds/static/css/style.css
fourwinds/static/sass/_pages.scss

- Added hover effects to collection items

Add hover effect to tours collection items

---

fourwinds/static/css/style.css
fourwinds/static/sass/_pages.scss
website/templates/website/website_contact_us_page.html
website/templates/website/website_get_quote_page.html

- Make page narrower
- Removed Email Us text
- Change button color to gold and changed text to Send Message

Enhance contact us page

---

fourwinds/static/css/style.css
fourwinds/static/sass/_header.scss

- Submenus are now open by default for easy access of child pages in mobile view

Show all links in mobile navbar

---

fourwinds/static/css/style.css
fourwinds/static/sass/_header.scss

- Fix white background when a submenu link is clicked in mobile view

Fix mobile view on link click white background

---

fourwinds/static/css/style.css
fourwinds/static/sass/_header.scss

- Fix submenu link goes to the next parent link when clicked

Fix link issues in mobile view navbar

---

website/templates/website/tags/testimonials.html

- Change heading of testimonials carousel

Change testimonials slider heading

---

fourwinds/static/css/style.css
fourwinds/static/sass/_landing.scss
fourwinds/static/sass/_pages.scss
website/templates/website/website_contact_us_page_landing.html
website/templates/website/website_get_quote_page_landing.html

- Enhanced submit button for both *contact form* and *get quote form*

Enhance form submit button

---

fourwinds/urls.py
website/mixins.py
website/models.py

- Fix error on viewing pdf in browser

Fix pdf preview in browser

---

fourwinds/urls.py
website/mixins.py

- refactor code of pdf preview into function only

Refactor code for pdf preview

---

fourwinds/settings/dev.py

- Fix email backend in dev settings

Fix email backend

---

website/templates/website/website_get_quote_page.html

Change types of trip

---

website/templates/website/website_get_quote_page.html

- Remove value for *Please select* option

Remove value in default select option

---

website/models.py
website/templates/website/website_contact_us_page_landing.html

- Fix redirect on success of contact us page

Fix on success redirect of contact page

---

website/models.py
website/templates/email/get-a-quote-template.html

- Add number of days to email submission

Add number of days to email submission

---

fourwinds/static/css/style.css
fourwinds/static/sass/_pages.scss
website/models.py
website/templates/website/website_full_content_page.html

- Added social media icons in thank you pages

Add social icons to thank you pages
